server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      connect-string: 192.168.0.106:2181

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://123.56.216.117:3306/vetech?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: vetech
    password: 123qwe!@#QWE

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.lemon.springcloud.entity    # 所有Entity别名类所在包


## zookeeper配置



