server:
  port: 9006
spring:
  application:
    name: cloud-gateway-zuul


eureka:
  client:
    service-url:
      # 修改成单机版本的配置
      defaultZone: http://eureka7001.com:7001/eureka
#zuul:
#  ignored-services: '*'
#  routes:
#    users: /pay/**


zuul:
  routes:
    pay:
      path: /pay/**
      serviceId: cloud-payment-service  #当只有几个服务的时候可以这样指定，当有几百个服务的时候怎么去设置
  prefix: /api
  strip-prefix: true #代理前缀