server:
  port: 8002

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://123.56.216.117:3306/vetech?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: vetech
    password: 123qwe!@#QWE

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.lemon.springcloud.entity    # 所有Entity别名类所在包


eureka:
  client:
    service-url:

      # fixme 如果配置的eureka集群这个地方要怎么配置，
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka

    #  表示是否将自己注册到eureka中
    register-with-eureka: true

    # 是否从eurekaServer中抓取已注册信息，默认为true，单节点无所谓，多节点必须设置为true才能配置ribbon使用负载均衡
    fetch-registry: true

  instance:
    instance-id: payment8002
    prefer-ip-address: true #访问路径可以显示ip地址


