server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    service-url:

      # fixme 如果配置的eureka集群这个地方要怎么配置，
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka

    #  表示是否将自己注册到eureka中
    register-with-eureka: true

    # 是否从eurekaServer中抓取已注册信息，默认为true，单节点无所谓，多节点必须设置为true才能配置ribbon使用负载均衡
    fetch-registry: true

# 设置feign客户端超时时间,
#ribbon:
  # 建立连接所用的时间   5秒
#   ReadTimeout: 5000

  # 建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true